[package]
name = "iris"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1.2"
thiserror = "1.0"
avro-rs = "0.13"
hex = "0.4.3"
num-bigint = "0.2.6"
num-traits = "0.2.19"
sha2 = "0.10.8"
base64 = "0.22.1"

bundlr-sdk = { git = "https://github.com/Salka1988/bundlr-sdk", branch = "salka1988/add_data_item"}
